name: Continuous Integration

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
      - edited

jobs:
  banana:
    name: banana
    runs-on: ubuntu-latest
    steps:
      - env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
  ci:
    if: github.event.pull_request.base.repo.organization == 'eips-wg'
    uses: eips-wg/build/.github/workflows/ci.yml@master
    secrets: inherit
