name: Review Trigger

on:
  pull_request_target:
  pull_request_review:
  workflow_dispatch:
    inputs:
      pr_number:
        description: Pull Request Number
        type: string
        required: true
  issue_comment:
    types:
      - created

jobs:
  review-trigger:
    if: github.event.repository.owner.login == 'eips-wg'
    uses: eips-wg/build/.github/workflows/review-trigger.yml@master
    secrets: inherit
