name: Review

on:
  workflow_run:
    workflows:
      - Review Trigger
    types:
      - completed

jobs:
  review:
    if: github.event.repository.owner.login == 'eips-wg'
    uses: eips-wg/build/.github/workflows/review.yml@master
    secrets: inherit

